name: Build and publish Docker image to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot**
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@integration-tests # FIXME: switch to main branch
    with:
      integration-test-enabled: false
      scanner-enabled: false
      strict-scanner: true
      integration-test-projects: "['cradle-admin-tool-cli','cradle-admin-tool-http']"
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}