name: Build and publish release Docker image to Github Container Registry ghcr.io

on: workflow_dispatch

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@integration-tests # FIXME: switch to main branch
    with:
      integration-test-enabled: true
      integration-test-projects: "['cradle-admin-tool-cli','cradle-admin-tool-http']"
      build-target: 'Docker'
      devRelease: false
      createTag: true
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}