name: Dev build and publish Docker image

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot*
    paths-ignore:
      - README.md
    # paths:
    # - gradle.properties

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      runsOn: ubuntu-latest
      gradleVersion: '7'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}



